name: redux_entity
description: Library for maintaining collections in a Redux store. Based on @ngrx/entity.
repository: https://github.com/careapp-inc/dart_redux_entity
version: 0.1.0
homepage: https://github.com/careapp-inc/dart_redux_entity

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  redux: ">= 3.0.0 < 5.0.0"
  test: ^1.6.0

dev_dependencies:
  mockito: ^4.1.1
  faker: ^1.1.1
  uuid: ^2.0.4
