name: redux_entity
description: Library for maintaining collections in a Redux store. Based on @ngrx/entity.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  redux: ">= 3.0.0 < 5.0.0"

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.6.0
  faker: ^1.1.1
  uuid: ^2.0.4
